# Gán nhãn

In [25]:
import pandas as pd
df = pd.read_csv("data.csv")
df

                                                   text
0     Từ học bổng thay đổi cuộc đời đến lớp học tiến...
1     Trường ĐH Tôn Đức Thắng công bố 4 nhóm nghiên ...
2     Đề thi thử tốt nghiệp THPT môn Toán của thành ...
3     Sở Giáo dục TPHCM lên tiếng việc 47.000 giáo v...
4     Người mẹ trăn trở trước giờ ghi 'đơn xanh' ngu...
...                                                 ...
2006  Khoảnh khắc đàn voi xếp vòng tròn bảo vệ con t...
2007  Biết bạn gái chống chọi bệnh tật suốt 20 năm, ...
2008  Bí mật phong thủy trong biệt phủ được xây suốt...
2009  Vườn hồng rực rỡ, rau trái sum sê trên sân thư...
2010  Cụ ông U80 gần 30 năm bán bánh trên vỉa hè, th...

[2011 rows x 1 columns]

In [5]:
# ==== 0) CÀI THƯ VIỆN (chạy 1 lần ngoài script)
# pip install snorkel pandas numpy

# ==== 1) IMPORTS & CẤU HÌNH ====
import re, unicodedata, numpy as np, pandas as pd
try:
    # new-ish API (preferred)
    from snorkel.labeling.model.label_model import LabelModel
    from snorkel.labeling.apply.pandas import PandasLFApplier
    from snorkel.labeling import labeling_function
except Exception:
    try:
        # older API surface
        from snorkel.labeling import LabelModel, PandasLFApplier, labeling_function
    except Exception:
        # fallback: try alternate locations
        from snorkel.labeling.model import LabelModel
        from snorkel.labeling.apply.pandas import PandasLFApplier
        from snorkel.labeling import labeling_function

INPUT_CSV = "data.csv"
OUTPUT_CSV = "data_labeled_snorkel.csv"
TEXT_COL = "text"  # ĐỔI nếu tên cột khác

# Nhãn cho Snorkel (giữ đúng thứ tự dùng xuyên suốt)
ABSTAIN, POS, NEG, NEU = -1, 0, 1, 2

# ==== 2) TIỆN ÍCH TIỀN XỬ LÝ ====
def strip_accents(s: str) -> str:
    if not isinstance(s, str): return ""
    s = s.replace("đ","d").replace("Đ","D")
    return "".join(ch for ch in unicodedata.normalize("NFKD", s) if not unicodedata.combining(ch))

def norm(s: str) -> str:
    s = strip_accents(s.lower().strip())
    s = re.sub(r"\s+"," ", s)
    return s

def contains_any(text: str, terms) -> bool:
    t = norm(text)
    for w in terms:
        # biên giới từ đơn giản để tránh dính từ khác
        if re.search(rf"\b{re.escape(norm(w))}\b", t):
            return True
    return False

def has_negation_near(text: str, terms, window: int = 4) -> bool:
    """Phát hiện phủ định gần cụm tích cực/tiêu cực trong cửa sổ ±window từ."""
    NEGATIONS = {"khong","ko","k","kg","chua","chua tung","chua he","chua duoc","chang","chong","phi"}
    toks = norm(text).split()
    if not toks: return False
    txt = " ".join(toks)
    # vị trí từng cụm từ cần xét
    for w in terms:
        pat = re.compile(rf"\b{re.escape(norm(w))}\b")
        for m in pat.finditer(txt):
            # xác định khoảng quanh cụm
            start_tok = len(txt[:m.start()].split())
            end_tok   = start_tok + len(norm(w).split()) - 1
            left = max(0, start_tok - window)
            right = min(len(toks)-1, end_tok + window)
            window_text = " ".join(toks[left:right+1])
            if any(re.search(rf"\b{re.escape(neg)}\b", window_text) for neg in NEGATIONS):
                return True
    return False

# ==== 3) BỘ TỪ KHÓA (mở rộng theo miền tin tức) ====
# POSITIVE (tin tốt / thành tựu / phúc lợi / khởi công - ra mắt)
POS_GENERAL = {
    "tich cuc","kha quan","dang mung","thuan loi","hieu qua","an toan","thanh cong",
    "ky luc","tang truong","phuc hoi","cai thien","vuot muc tieu","nang cap","phat trien",
    "vinh danh","duoc khen thuong","dat giai","giai thuong","xep hang cao","tien phong",
    "mo rong","giam phi","giam gia","uu dai","mien phi","ho tro","tro cap","an sinh",
    "phau thuat thanh cong","cuu tro","cuu song","giai cuu","ban giao","dua vao van hanh",
}
POS_EVENT = {
    "khoi cong","khoi dong","khai truong","khanh thanh","ra mat","ra mat san pham",
    "cong bo","phe duyet","thanh lap","tuyen dung","mo ban","mo cua tro lai",
    "thu nghiem thanh cong","de an duoc thong qua","trien khai","tiep suc","hoc bong",
}
POS_EDU_SCI = {
    "nhom nghien cuu manh","doi moi sang tao","chuyen doi so","dat chuan","duoc cong nhan",
    "hoc bong","do dau","dau bang","tang chi tieu tuyen sinh","dat chuan kiem dinh",
}
POS_HEALTH_SOC = {
    "giam benh","kiem soat dich","xoa ngheo","giam ngheo","tang muc song","tang phuc loi",
    "tang luong","tang phu cap","ho tro nguoi dan","bao hiem chi tra",
}

# NEGATIVE (su co / phap ly / suc khoe / kinh te-xa hoi)
NEG_DISASTER = {
    "chay","chay lon","no","sap","sat lo","ngap","lu lut","bao","dong dat","han han",
    "su co","thiet hai","khung hoang","doi dau","mat mat","nghiem trong","cap bach",
}
NEG_CRIME_LEGAL = {
    "lua dao","gia mao","hang gia","thuoc gia","sua gia","to cao","khoi to","bat tam giam",
    "tac trach","tieu cuc","tham nhung","hoa hong","hoi lo","vi pham","sai pham",
    "xu phat","truy to","xet xu","khieu nai","kien","don kien","tranh chap","be boi",
}
NEG_ECON_SOC = {
    "that nghiep","giam luong","thua lo","no xau","lam phat","roi loan","dinh tre","cham tien do",
    "qua tai","ac mong","bat thuong","bat on","bat cap","gay buc xuc","bat binh dang",
}
NEG_HEALTH = {
    "dich benh","bung phat","benh hiem ngheo","tu vong","chet","ngo doc","bong nang",
    "benh dai","benh so","benh nguy hiem","benh truyen nhiem","benh ung thu",
}
NEG_EVENT = {
    "vu chay","vu viec","vu no","tai nan","tien an","tien su","dot kich","ban chet",
    "trom cap","cuop giat","hiep dam","bau vat bi danh cap","gia do","lam gia giay to",
}

# NEUTRAL (tường thuật / cập nhật)
NEU_INFO = {
    "cap nhat","thong bao","huong dan","thong tin chi tiet","bao cao","thong ke","so lieu",
    "lich thi","de thi","dap an","tuyen sinh","phuong an","ke hoach","lich trinh","quy dinh",
    "van ban","du thao","de an","nghi quyet","toan canh","tong quan","tu lieu","ho so",
    "danh sach","top","xep hang","ai la","co phai","vi sao","bao nhieu","la gi",
}
NEU_FORMAT = {
    "anh","video","clip","podcast","livestream","ban tin","tuong thuat","phong su anh"
}

# Gom nhóm để tiện tạo nhiều LF
POS_GROUPS = [POS_GENERAL, POS_EVENT, POS_EDU_SCI, POS_HEALTH_SOC]
NEG_GROUPS = [NEG_DISASTER, NEG_CRIME_LEGAL, NEG_ECON_SOC, NEG_HEALTH, NEG_EVENT]
NEU_GROUPS = [NEU_INFO, NEU_FORMAT]

# ==== 4) TẠO LABELING FUNCTIONS TỪ TỪ KHÓA ====
def make_kw_lf(name: str, terms: set, label: int):
    @labeling_function(name=name)
    def _lf(x):
        return label if contains_any(x.text, terms) else ABSTAIN
    return _lf

LFs = []
# Positive LFs
for i, terms in enumerate(POS_GROUPS, 1):
    LFs.append(make_kw_lf(f"lf_pos_kw_{i}", terms, POS))

# Negative LFs
for i, terms in enumerate(NEG_GROUPS, 1):
    LFs.append(make_kw_lf(f"lf_neg_kw_{i}", terms, NEG))

# Neutral LFs
for i, terms in enumerate(NEU_GROUPS, 1):
    LFs.append(make_kw_lf(f"lf_neu_kw_{i}", terms, NEU))

# Phủ định gần cụm POS => NEG
@labeling_function()
def lf_negation_flip_pos(x):
    return NEG if has_negation_near(x.text, set().union(*POS_GROUPS)) else ABSTAIN

# (tùy) Phủ định gần cụm NEG => POS (ít gặp trong báo chí, nhưng vẫn có)
@labeling_function()
def lf_negation_flip_neg(x):
    return POS if has_negation_near(x.text, set().union(*NEG_GROUPS)) else ABSTAIN

# Tiêu đề/câu hỏi nghi vấn → thường NEU (trừ khi đã trúng POS/NEG ở LFs khác)
@labeling_function()
def lf_question_neu(x):
    t = norm(x.text)
    return NEU if ("?" in x.text or t.startswith(("ai ","co phai ","vi sao ","tai sao ","bao nhieu ","la gi "))) else ABSTAIN

LFs.extend([lf_negation_flip_pos, lf_negation_flip_neg, lf_question_neu])

# ==== 5) ĐỌC DỮ LIỆU ====
df = pd.read_csv(INPUT_CSV)
assert TEXT_COL in df.columns, f"Khong tim thay cot '{TEXT_COL}' trong {INPUT_CSV}"
df = df[[TEXT_COL]].rename(columns={TEXT_COL: "text"})

# ==== 6) ÁP DỤNG LFs & HUẤN LUYỆN LABELMODEL ====
applier = PandasLFApplier(lfs=LFs)
L = applier.apply(df=df)

label_model = LabelModel(cardinality=3, verbose=False)
label_model.fit(L_train=L, n_epochs=500, log_freq=100, seed=7)

# ==== 7) DỰ ĐOÁN & LƯU KẾT QUẢ ====
probs = label_model.predict_proba(L)  # cột theo thứ tự [POS, NEG, NEU]
preds = label_model.predict(L)

out = df.copy()
out[["p_pos","p_neg","p_neu"]] = probs
out["pred_label"] = np.where(preds==POS,"positive", np.where(preds==NEG,"negative","neutral"))
out["confidence"] = out[["p_pos","p_neg","p_neu"]].max(axis=1)
out.to_csv(OUTPUT_CSV, index=False)

print("Phân bố nhãn dự đoán:")
print(out["pred_label"].value_counts(dropna=False))
print(f"\nDa luu: {OUTPUT_CSV}")
print("Goi y review tay: so dong co confidence < 0.5 =", (out["confidence"] < 0.5).sum())

100%|██████████| 2011/2011 [00:15<00:00, 130.10it/s]
100%|██████████| 500/500 [00:00<00:00, 546.44epoch/s]

Phân bố nhãn dự đoán:
pred_label
neutral     833
negative    746
positive    432
Name: count, dtype: int64

Da luu: data_labeled_snorkel.csv
Goi y review tay: so dong co confidence < 0.5 = 1688

In [6]:
import pandas as pd
df = pd.read_csv("data_labeled_snorkel.csv")
df

,text,p_pos,p_neg,p_neu,pred_label,confidence
0,Từ học bổng thay đổi cuộc đời đến lớp học tiến...,0.585788,0.140232,0.273980,positive,0.585788
1,Trường ĐH Tôn Đức Thắng công bố 4 nhóm nghiên ...,0.731767,0.086567,0.181665,positive,0.731767
2,Đề thi thử tốt nghiệp THPT môn Toán của thành ...,0.319372,0.327784,0.352844,neutral,0.352844
3,Sở Giáo dục TPHCM lên tiếng việc 47.000 giáo v...,0.276561,0.371214,0.352225,negative,0.371214
4,Người mẹ trăn trở trước giờ ghi 'đơn xanh' ngu...,0.333333,0.333333,0.333333,neutral,0.333333
...,...,...,...,...,...,...
2006,Khoảnh khắc đàn voi xếp vòng tròn bảo vệ con t...,0.288214,0.397262,0.314524,negative,0.397262
2007,"Biết bạn gái chống chọi bệnh tật suốt 20 năm, ...",0.333333,0.333333,0.333333,neutral,0.333333
2008,Bí mật phong thủy trong biệt phủ được xây suốt...,0.333333,0.333333,0.333333,neutral,0.333333
2009,"Vườn hồng rực rỡ, rau trái sum sê trên sân thư...",0.313203,0.379658,0.307140,negative,0.379658
2010,"Cụ ông U80 gần 30 năm bán bánh trên vỉa hè, th...",0.333333,0.333333,0.333333,neutral,0.333333

In [ ]:
# -*- coding: utf-8 -*-
# Crawl keywords POS/NEG từ VietNamNet theo dải ngày & cate, sau đó gán nhãn data.csv
# Yêu cầu: requests, beautifulsoup4, pandas, numpy, snorkel, tqdm

import re, time, json, unicodedata, sys
from collections import defaultdict
from datetime import datetime, timedelta
from typing import List, Dict, Set
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from tqdm import tqdm

# ================== CẤU HÌNH ==================
START_DATE = "12/04/2025"   # dd/mm/yyyy
END_DATE   = "18/10/2025"   # dd/mm/yyyy

BASE = "https://vietnamnet.vn/tin-tuc-24h"
CATE_CODES = [
    "000006","00000R","00000E","000001","00MK8V","000007","00000U","000003",
    "00000B","000008","00000W","000005","000009","000002","00M7F7","00000T","000004"
]

INPUT_CSV  = "data.csv"                   # file dữ liệu của bạn
OUTPUT_CSV = "data_labeled_snorkel.csv"   # file xuất kết quả

HEADERS = {"User-Agent": "Mozilla/5.0 (keyword-miner/1.0)"}
ARTICLE_HREF_RE = re.compile(r"/[a-z0-9\-]+-\d+\.html$")  # ...-2454143.html

# ================== TIỆN ÍCH CHUẨN HÓA ==================
def strip_accents(s: str) -> str:
    if not isinstance(s, str): return ""
    s = s.replace("đ","d").replace("Đ","D")
    return "".join(ch for ch in unicodedata.normalize("NFKD", s) if not unicodedata.combining(ch))

def norm(s: str) -> str:
    s = strip_accents(s.lower().strip())
    s = re.sub(r"\s+"," ", s)
    return s

def contains_any(text: str, terms: Set[str]) -> bool:
    t = norm(text)
    for w in terms:
        if re.search(rf"\b{re.escape(norm(w))}\b", t):
            return True
    return False

def has_negation_near(text: str, terms: Set[str], window: int = 4) -> bool:
    NEGATIONS = {"khong","ko","k","kg","chua","chua tung","chua he","chua duoc","chang"}
    toks = norm(text).split()
    if not toks: return False
    txt = " ".join(toks)
    for w in terms:
        pat = re.compile(rf"\b{re.escape(norm(w))}\b")
        for m in pat.finditer(txt):
            start_tok = len(txt[:m.start()].split())
            end_tok   = start_tok + len(norm(w).split()) - 1
            left = max(0, start_tok - window)
            right = min(len(toks)-1, end_tok + window)
            window_text = " ".join(toks[left:right+1])
            if any(re.search(rf"\b{re.escape(neg)}\b", window_text) for neg in NEGATIONS):
                return True
    return False

# ================== SEED LEXICON (mở rộng theo báo chí) ==================
SEED_POS = {
    "tich cuc","kha quan","dang mung","thuan loi","hieu qua","an toan","thanh cong",
    "ky luc","tang truong","phuc hoi","cai thien","vuot muc tieu","nang cap","phat trien",
    "vinh danh","khen thuong","dat giai","giai thuong","xep hang cao","tien phong",
    "mo rong","giam phi","giam gia","uu dai","mien phi","ho tro","tro cap","an sinh",
    "ban giao","dua vao van hanh","ky ket","hop tac","hop dong lon","goi von","ipo thanh cong",
    "loi nhuan ky luc","doanh thu ky luc","khoi sac","phuc hoi manh","trung thau","giai ngan",
    "khoi cong","khoi dong","khai truong","khanh thanh","ra mat","cong bo","phe duyet","thanh lap",
    "mo ban","mo cua tro lai","thu nghiem thanh cong","de an duoc thong qua","trien khai",
    "tiep suc","hoc bong","nhom nghien cuu manh","doi moi sang tao","chuyen doi so",
    "dat chuan","duoc cong nhan","do dau","dau bang","tang chi tieu tuyen sinh","dat chuan kiem dinh",
    "phau thuat thanh cong","ghep tang thanh cong","khoi benh","xuat vien","kiem soat dich",
    "xoa ngheo","giam ngheo","tang muc song","tang phuc loi","tang luong","tang phu cap",
    "bao hiem chi tra","cuu tro","cuu song","giai cuu",
    "gianh chien thang","chien thang","vo dich","len ngoi","pha ky luc","vao chung ket",
    "thang dam","thang sat nut","thang nhe","thang quan",
    "dong khach","chay ve","doat giai","giai thuong quoc te","ra mat phim","ra mat mv",
    "mo ban du an","ban giao nha","ban giao so","giam lai suat","phe duyet quy hoach",
    "ban cap nhat","ban va","phat song","phu song","ra mat ung dung"
}

SEED_NEG = {
    "chay","chay lon","no","sap","sat lo","ngap","lu lut","bao","dong dat","han han","su co","thiet hai",
    "khung hoang","bat on","bat thuong","cap bach","dot bien xau",
    "lua dao","gia mao","hang gia","thuoc gia","sua gia","to cao","khoi to","bat tam giam",
    "tac trach","tieu cuc","tham nhung","hoi lo","vi pham","sai pham","xu phat","truy to","xet xu",
    "khieu nai","kien","don kien","tranh chap","be boi","truy na","an mang",
    "that nghiep","giam luong","thua lo","no xau","lam phat","roi loan","dinh tre","cham tien do",
    "qua tai","giam manh","giam sau","suy giam","suy thoai","khong dat","tut doc",
    "dich benh","bung phat","o dich","benh hiem ngheo","ngo doc","tu vong","chet","sot xuat huyet",
    "sap mang","sap he thong","lo hong","lo hong bao mat","ro ri du lieu","tan cong mang","ransomware","bi hack",
    "tin gia","mao danh","lua dao truc tuyen","spam",
    "trieu hoi xe","tai nan","lat xe","dieu tra nguyen nhan",
    "chat chem","ket xe","qua tai khach","tai nan du lich",
    "lo de","gian lan thi cu","bao luc hoc duong",
    "thua dam","bi loai","dut mach thang","chan thuong nang",
    "thoi gia","sot dat","bong bong","du an ma","ket phap ly","cham cap so","cuong che","tranh chap dat dai",
    "lum xum","be boi","bi chi trich","tay chay"
}

NEU_HINTS = {
    "cap nhat","thong bao","huong dan","bao cao","thong ke","so lieu",
    "lich thi","de thi","dap an","tuyen sinh","ke hoach","lich trinh","quy dinh",
    "danh sach","top","xep hang","ai la","co phai","vi sao","bao nhieu","la gi","hoi dap"
}

# ================== CRAWL THEO DẢI NGÀY & CATE ==================
def iter_dates(start_str: str, end_str: str):
    s = datetime.strptime(start_str, "%d/%m/%Y")
    e = datetime.strptime(end_str, "%d/%m/%Y")
    d = s
    while d <= e:
        yield d.strftime("%d/%m/%Y")
        d += timedelta(days=1)

def fetch_titles_for_cate(cate: str, bydate: str) -> List[str]:
    url = f"{BASE}?bydate={requests.utils.quote(bydate, safe='')}&cate={cate}"
    for attempt in range(3):
        try:
            r = requests.get(url, headers=HEADERS, timeout=20)
            r.raise_for_status()
            soup = BeautifulSoup(r.text, "html.parser")
            titles = set()
            for a in soup.find_all("a", href=True):
                href = a["href"]
                if ARTICLE_HREF_RE.search(href):
                    text = a.get_text(strip=True)
                    if text:
                        titles.add(text)
            return list(titles)
        except Exception:
            if attempt == 2:
                return []
            time.sleep(1.0 + attempt * 1.0)
    return []

def collect_keywords_range(start_date: str, end_date: str, cate_codes: List[str]):
    pos_by_cate = {c: set() for c in cate_codes}
    neg_by_cate = {c: set() for c in cate_codes}
    total_titles = 0

    for day in tqdm(list(iter_dates(start_date, end_date)), desc="Days"):
        bydate = f"{day}-{day}"
        for cate in tqdm(cate_codes, desc=f"cate", leave=False):
            titles = fetch_titles_for_cate(cate, bydate)
            total_titles += len(titles)
            # trích keyword xuất hiện
            for t in titles:
                tnorm = norm(t)
                for w in SEED_POS:
                    if re.search(rf"\b{re.escape(norm(w))}\b", tnorm):
                        pos_by_cate[cate].add(w)
                for w in SEED_NEG:
                    if re.search(rf"\b{re.escape(norm(w))}\b", tnorm):
                        neg_by_cate[cate].add(w)
            time.sleep(0.2)  # lịch sự
    return {
        "pos_by_cate": {k: sorted(v) for k, v in pos_by_cate.items()},
        "neg_by_cate": {k: sorted(v) for k, v in neg_by_cate.items()},
        "meta": {"start": start_date, "end": end_date, "total_titles_seen": total_titles}
    }

print("==> Bắt đầu crawl từ", START_DATE, "đến", END_DATE)
kw = collect_keywords_range(START_DATE, END_DATE, CATE_CODES)

with open("vnnet_keywords_range.json", "w", encoding="utf-8") as f:
    json.dump(kw, f, ensure_ascii=False, indent=2)
print("Đã lưu vnnet_keywords_range.json")

# Hợp nhất keyword POS/NEG thực sự gặp trong dải ngày
pos_union = sorted(set().union(*[set(v) for v in kw["pos_by_cate"].values()])) if kw["pos_by_cate"] else []
neg_union = sorted(set().union(*[set(v) for v in kw["neg_by_cate"].values()])) if kw["neg_by_cate"] else []
print(f"POS found (union): {len(pos_union)} | NEG found (union): {len(neg_union)}")

# ================== PHẦN GÁN NHÃN ==================
# Thử import Snorkel (robust qua nhiều phiên bản); nếu fail -> fallback rule-based
SNORKEL_OK = True
try:
    from snorkel.labeling.model.label_model import LabelModel
    from snorkel.labeling.apply.pandas import PandasLFApplier
    from snorkel.labeling import labeling_function
except Exception:
    try:
        from snorkel.labeling import LabelModel, PandasLFApplier, labeling_function
    except Exception:
        try:
            from snorkel.labeling.model import LabelModel
            from snorkel.labeling.apply.pandas import PandasLFApplier
            from snorkel.labeling import labeling_function
        except Exception as e:
            print("[WARN] Snorkel import failed -> dùng fallback rule-based. Lý do:", e)
            SNORKEL_OK = False

ABSTAIN, POS, NEG, NEU = -1, 0, 1, 2
POS_TERMS = set(SEED_POS).union(pos_union)
NEG_TERMS = set(SEED_NEG).union(neg_union)

# Đọc dữ liệu cần gán nhãn
df = pd.read_csv(INPUT_CSV)
if "text" not in df.columns:
    raise ValueError("Không thấy cột 'text' trong data.csv. Hãy đổi tên cột văn bản thành 'text' hoặc sửa code.")

# ---- NEU hints (kéo về neutral khi không có polar rõ)
def lf_neu_hint_func(text: str) -> bool:
    return contains_any(text, NEU_HINTS)

if SNORKEL_OK:
    # === Snorkel LFs ===
    @labeling_function()
    def lf_pos_kw(x):
        return POS if contains_any(x.text, POS_TERMS) else ABSTAIN

    @labeling_function()
    def lf_neg_kw(x):
        return NEG if contains_any(x.text, NEG_TERMS) else ABSTAIN

    @labeling_function()
    def lf_negation_flip_pos(x):
        return NEG if has_negation_near(x.text, POS_TERMS) else ABSTAIN

    @labeling_function()
    def lf_negation_flip_neg(x):
        return POS if has_negation_near(x.text, NEG_TERMS) else ABSTAIN

    @labeling_function()
    def lf_neu_fallback(x):
        return NEU if lf_neu_hint_func(x.text) else ABSTAIN

    LFs = [lf_pos_kw, lf_neg_kw, lf_negation_flip_pos, lf_negation_flip_neg, lf_neu_fallback]

    df_ = df[["text"]].copy()
    applier = PandasLFApplier(lfs=LFs)
    L = applier.apply(df=df_)

    label_model = LabelModel(cardinality=3, verbose=False)
    label_model.fit(L_train=L, n_epochs=500, log_freq=100, seed=7)

    probs = label_model.predict_proba(L)  # [POS, NEG, NEU]
    preds = label_model.predict(L)

    out = df.copy()
    out[["p_pos","p_neg","p_neu"]] = probs
    out["pred_label"] = np.where(preds==POS,"positive", np.where(preds==NEG,"negative","neutral"))
    out["confidence"] = out[["p_pos","p_neg","p_neu"]].max(axis=1)
else:
    # === Fallback rule-based (không cần Snorkel) ===
    def score_rule(text: str):
        t = norm(text)
        pos = sum(1 for w in POS_TERMS if re.search(rf"\b{re.escape(norm(w))}\b", t))
        neg = sum(1 for w in NEG_TERMS if re.search(rf"\b{re.escape(norm(w))}\b", t))
        # phủ định gần
        if has_negation_near(text, POS_TERMS): neg += 1
        if has_negation_near(text, NEG_TERMS): pos += 1
        neu = 1 if lf_neu_hint_func(text) else 0
        return {"pos": pos, "neg": neg, "neu": neu}

    scores = df["text"].apply(score_rule)
    out = df.copy()
    out["p_pos"] = scores.apply(lambda s: s["pos"])
    out["p_neg"] = scores.apply(lambda s: s["neg"])
    out["p_neu"] = scores.apply(lambda s: s["neu"])
    # chuẩn hóa pseudo-prob
    sm = (out[["p_pos","p_neg","p_neu"]].sum(axis=1) + 1e-9)
    out[["p_pos","p_neg","p_neu"]] = out[["p_pos","p_neg","p_neu"]].div(sm, axis=0)
    out["pred_label"] = out[["p_pos","p_neg","p_neu"]].idxmax(axis=1).map({"p_pos":"positive","p_neg":"negative","p_neu":"neutral"})
    out["confidence"] = out[["p_pos","p_neg","p_neu"]].max(axis=1)

# Xuất kết quả
out.to_csv(OUTPUT_CSV, index=False)
print("\n==> PHÂN BỐ NHÃN:")
print(out["pred_label"].value_counts(dropna=False))
print("Đã lưu:", OUTPUT_CSV)
print("Gợi ý review tay (confidence < 0.5):", int((out["confidence"] < 0.5).sum()))

In [2]:
# Re-run the full pipeline to read ./data.csv, extract POS/NEG terms present,
# and label with Snorkel LabelModel (fallback to rule-based if Snorkel unavailable).
import pandas as pd, re, json, unicodedata
import numpy as np
from collections import Counter

def strip_accents(s: str) -> str:
    if not isinstance(s, str): 
        return ""
    s = s.replace("đ","d").replace("Đ","D")
    return "".join(ch for ch in unicodedata.normalize("NFKD", s) if not unicodedata.combining(ch))

def norm(s: str) -> str:
    s = strip_accents(s.lower().strip())
    s = re.sub(r"\s+"," ", s)
    return s

def contains_any(text: str, terms) -> bool:
    t = norm(text)
    for w in terms:
        if re.search(rf"\b{re.escape(norm(w))}\b", t):
            return True
    return False

def has_negation_near(text: str, terms, window: int = 4) -> bool:
    NEGATIONS = {"khong","ko","k","kg","chua","chua tung","chua he","chua duoc","chang"}
    toks = norm(text).split()
    if not toks: return False
    txt = " ".join(toks)
    for w in terms:
        pat = re.compile(rf"\b{re.escape(norm(w))}\b")
        for m in pat.finditer(txt):
            start_tok = len(txt[:m.start()].split())
            end_tok   = start_tok + len(norm(w).split()) - 1
            left = max(0, start_tok - window)
            right = min(len(toks)-1, end_tok + window)
            window_text = " ".join(toks[left:right+1])
            if any(re.search(rf"\b{re.escape(neg)}\b", window_text) for neg in NEGATIONS):
                return True
    return False

# Load CSV
csv_path = "./data.csv"
df = pd.read_csv(csv_path)

# Detect text column
text_col = None
for c in ["text", "title", "headline", "content"]:
    if c in df.columns:
        text_col = c
        break
if text_col is None:
    for c in df.columns:
        if df[c].dtype == "object":
            text_col = c
            break
if text_col is None:
    raise ValueError("Không thấy cột văn bản ('text'/'title'/'headline'/'content').")

df = df[df[text_col].notna()].copy()
df["_text_norm"] = df[text_col].apply(norm)

# Seed lexicons
SEED_POS = {
    "tich cuc","kha quan","dang mung","thuan loi","hieu qua","an toan","thanh cong",
    "ky luc","tang truong","phuc hoi","cai thien","vuot muc tieu","nang cap","phat trien",
    "vinh danh","khen thuong","dat giai","giai thuong","xep hang cao","tien phong",
    "mo rong","giam phi","giam gia","uu dai","mien phi","ho tro","tro cap","an sinh",
    "ban giao","dua vao van hanh","ky ket","hop tac","hop dong lon","goi von","ipo thanh cong",
    "loi nhuan ky luc","doanh thu ky luc","khoi sac","phuc hoi manh","trung thau","giai ngan",
    "khoi cong","khoi dong","khai truong","khanh thanh","ra mat","cong bo","phe duyet","thanh lap",
    "mo ban","mo cua tro lai","thu nghiem thanh cong","de an duoc thong qua","trien khai",
    "tiep suc","hoc bong","nhom nghien cuu manh","doi moi sang tao","chuyen doi so",
    "dat chuan","duoc cong nhan","do dau","dau bang","tang chi tieu tuyen sinh","dat chuan kiem dinh",
    "phau thuat thanh cong","ghep tang thanh cong","khoi benh","xuat vien","kiem soat dich",
    "xoa ngheo","giam ngheo","tang muc song","tang phuc loi","tang luong","tang phu cap",
    "bao hiem chi tra","cuu tro","cuu song","giai cuu",
    "gianh chien thang","chien thang","vo dich","len ngoi","pha ky luc","vao chung ket",
    "thang dam","thang sat nut","thang nhe","thang quan",
    "dong khach","chay ve","doat giai","giai thuong quoc te","ra mat phim","ra mat mv",
    "mo ban du an","ban giao nha","ban giao so","giam lai suat","phe duyet quy hoach",
    "ban cap nhat","phat song","phu song","ra mat ung dung"
}

SEED_NEG = {
    "chay","chay lon","no","sap","sat lo","ngap","lu lut","bao","dong dat","han han","su co","thiet hai",
    "khung hoang","bat on","bat thuong","cap bach","dot bien xau",
    "lua dao","gia mao","hang gia","thuoc gia","sua gia","to cao","khoi to","bat tam giam",
    "tac trach","tieu cuc","tham nhung","hoi lo","vi pham","sai pham","xu phat","truy to","xet xu",
    "khieu nai","kien","don kien","tranh chap","be boi","truy na","an mang",
    "that nghiep","giam luong","thua lo","no xau","lam phat","roi loan","dinh tre","cham tien do",
    "qua tai","giam manh","giam sau","suy giam","suy thoai","khong dat","tut doc",
    "dich benh","bung phat","o dich","benh hiem ngheo","ngo doc","tu vong","chet","sot xuat huyet",
    "sap mang","sap he thong","lo hong","lo hong bao mat","ro ri du lieu","tan cong mang","ransomware","bi hack",
    "tin gia","mao danh","lua dao truc tuyen","spam",
    "trieu hoi xe","tai nan","lat xe","dieu tra nguyen nhan",
    "chat chem","ket xe","qua tai khach","tai nan du lich",
    "lo de","gian lan thi cu","bao luc hoc duong",
    "thua dam","bi loai","dut mach thang","chan thuong nang",
    "thoi gia","sot dat","bong bong","du an ma","ket phap ly","cham cap so","cuong che","tranh chap dat dai",
    "lum xum","be boi","bi chi trich","tay chay"
}

NEU_HINTS = {
    "cap nhat","thong bao","huong dan","bao cao","thong ke","so lieu",
    "lich thi","de thi","dap an","tuyen sinh","ke hoach","lich trinh","quy dinh",
    "danh sach","top","xep hang","ai la","co phai","vi sao","bao nhieu","la gi","hoi dap"
}

# Which terms appear in data?
def find_terms_in_corpus(texts_norm, term_set):
    found = Counter()
    for t in texts_norm:
        for w in term_set:
            if re.search(rf"\b{re.escape(norm(w))}\b", t):
                found[w] += 1
    return found

pos_found = find_terms_in_corpus(df["_text_norm"], SEED_POS)
neg_found = find_terms_in_corpus(df["_text_norm"], SEED_NEG)

pos_terms_sorted = [k for k,_ in pos_found.most_common()]
neg_terms_sorted = [k for k,_ in neg_found.most_common()]

with open("./pos_terms_found.json","w",encoding="utf-8") as f:
    json.dump({"pos_terms": pos_terms_sorted, "counts": pos_found}, f, ensure_ascii=False, indent=2)
with open("./neg_terms_found.json","w",encoding="utf-8") as f:
    json.dump({"neg_terms": neg_terms_sorted, "counts": neg_found}, f, ensure_ascii=False, indent=2)

# Try Snorkel
SNORKEL_OK = True
try:
    from snorkel.labeling.model.label_model import LabelModel
    from snorkel.labeling.apply.pandas import PandasLFApplier
    from snorkel.labeling import labeling_function
except Exception:
    try:
        from snorkel.labeling import LabelModel, PandasLFApplier, labeling_function
    except Exception:
        try:
            from snorkel.labeling.model import LabelModel
            from snorkel.labeling.apply.pandas import PandasLFApplier
            from snorkel.labeling import labeling_function
        except Exception as e:
            SNORKEL_OK = False
            snorkel_err = str(e)

ABSTAIN, POS, NEG, NEU = -1, 0, 1, 2
POS_TERMS = set(pos_terms_sorted) if pos_terms_sorted else SEED_POS
NEG_TERMS = set(neg_terms_sorted) if neg_terms_sorted else SEED_NEG

def lf_neu_hint_func(text: str) -> bool:
    return contains_any(text, NEU_HINTS)

if SNORKEL_OK:
    @labeling_function()
    def lf_pos_kw(x):
        return POS if contains_any(x[text_col], POS_TERMS) else ABSTAIN

    @labeling_function()
    def lf_neg_kw(x):
        return NEG if contains_any(x[text_col], NEG_TERMS) else ABSTAIN

    @labeling_function()
    def lf_negation_flip_pos(x):
        return NEG if has_negation_near(x[text_col], POS_TERMS) else ABSTAIN

    @labeling_function()
    def lf_negation_flip_neg(x):
        return POS if has_negation_near(x[text_col], NEG_TERMS) else ABSTAIN

    @labeling_function()
    def lf_neu_fallback(x):
        return NEU if lf_neu_hint_func(x[text_col]) else ABSTAIN

    LFs = [lf_pos_kw, lf_neg_kw, lf_negation_flip_pos, lf_negation_flip_neg, lf_neu_fallback]

    applier = PandasLFApplier(lfs=LFs)
    L = applier.apply(df=df[[text_col]])

    label_model = LabelModel(cardinality=3, verbose=False)
    label_model.fit(L_train=L, n_epochs=500, log_freq=100, seed=7)

    probs = label_model.predict_proba(L)  # [POS, NEG, NEU]
    preds = label_model.predict(L)

    out = df.copy()
    out[["p_pos","p_neg","p_neu"]] = probs
    out["pred_label"] = np.where(preds==POS,"positive", np.where(preds==NEG,"negative","neutral"))
    out["confidence"] = out[["p_pos","p_neg","p_neu"]].max(axis=1)
    out_path = "./data_labeled_snorkel.csv"
    out.to_csv(out_path, index=False)
    snorkel_status = "Snorkel LabelModel: OK"
else:
    # Fallback: majority-like
    def score_rule(text: str):
        t = norm(text)
        pos = sum(1 for w in POS_TERMS if re.search(rf"\b{re.escape(norm(w))}\b", t))
        neg = sum(1 for w in NEG_TERMS if re.search(rf"\b{re.escape(norm(w))}\b", t))
        if has_negation_near(text, POS_TERMS): neg += 1
        if has_negation_near(text, NEG_TERMS): pos += 1
        neu = 1 if lf_neu_hint_func(text) else 0
        return {"pos":pos, "neg":neg, "neu":neu}

    scores = df[text_col].apply(score_rule)
    out = df.copy()
    out["p_pos"] = scores.apply(lambda s: s["pos"])
    out["p_neg"] = scores.apply(lambda s: s["neg"])
    out["p_neu"] = scores.apply(lambda s: s["neu"])
    sm = (out[["p_pos","p_neg","p_neu"]].sum(axis=1) + 1e-9)
    out[["p_pos","p_neg","p_neu"]] = out[["p_pos","p_neg","p_neu"]].div(sm, axis=0)
    out["pred_label"] = out[["p_pos","p_neg","p_neu"]].idxmax(axis=1).map({"p_pos":"positive","p_neg":"negative","p_neu":"neutral"})
    out["confidence"] = out[["p_pos","p_neg","p_neu"]].max(axis=1)
    out_path = "./data_labeled_snorkel.csv"
    out.to_csv(out_path, index=False)
    snorkel_status = f"Snorkel LabelModel: NOT AVAILABLE; used fallback."

# Show small preview
preview = out[[text_col, "pred_label", "p_pos","p_neg","p_neu","confidence"]].head(20)

preview

100%|██████████| 2011/2011 [00:12<00:00, 156.28it/s]
100%|██████████| 500/500 [00:00<00:00, 596.22epoch/s]

,text,pred_label,p_pos,p_neg,p_neu,confidence
0,Từ học bổng thay đổi cuộc đời đến lớp học tiến...,positive,0.394536,0.276980,0.328484,0.394536
1,Trường ĐH Tôn Đức Thắng công bố 4 nhóm nghiên ...,positive,0.394536,0.276980,0.328484,0.394536
2,Đề thi thử tốt nghiệp THPT môn Toán của thành ...,neutral,0.332652,0.303936,0.363412,0.363412
3,Sở Giáo dục TPHCM lên tiếng việc 47.000 giáo v...,neutral,0.333333,0.333333,0.333333,0.333333
4,Người mẹ trăn trở trước giờ ghi 'đơn xanh' ngu...,neutral,0.333333,0.333333,0.333333,0.333333
5,"Tốt nghiệp loại giỏi dù không biết đọc viết, n...",negative,0.294307,0.395404,0.310289,0.395404
6,Màn ‘hỏi xoáy’ bất ngờ của học sinh BRIS với g...,neutral,0.333333,0.333333,0.333333,0.333333
7,Tổng Bí thư gợi mở miễn phí bữa trưa cho học s...,positive,0.354485,0.334350,0.311165,0.354485
8,Top 10 trường có điểm chuẩn lớp 10 cao nhất TP...,neutral,0.332652,0.303936,0.363412,0.363412
9,"Ai là người vẽ bản đồ tác chiến Xuân Lộc 1975,...",positive,0.392002,0.251444,0.356553,0.392002
10,Bé Nguyễn Tú Uyên đã được phẫu thuật tim thành...,positive,0.394536,0.276980,0.328484,0.394536
11,"Con trai suy tuỷ xương, mẹ đơn thân bế tắc khô...",negative,0.294307,0.395404,0.310289,0.395404
12,Có phải làm lại sổ đỏ sau sáp nhập tỉnh; ông c...,negative,0.295917,0.363248,0.340835,0.363248
13,Đồng Nai sắp có khu nghỉ dưỡng quy mô gần 18.0...,positive,0.354485,0.334350,0.311165,0.354485
14,Xây nhà ở nhiều năm trên đất khai hoang có đượ...,neutral,0.333333,0.333333,0.333333,0.333333
15,"Phó Thủ tướng: Sữa giả, thuốc giả gây bức xúc ...",negative,0.294307,0.395404,0.310289,0.395404
16,Từ chiến sĩ nặng 40kg đến người vẽ bản đồ tác ...,neutral,0.333333,0.333333,0.333333,0.333333
17,Thủ tướng: Khởi công đường sắt TPHCM - Cần Thơ...,positive,0.394536,0.276980,0.328484,0.394536
18,Thủy thủ tàu ngầm đọc sách giữa lòng đại dương...,neutral,0.333333,0.333333,0.333333,0.333333
19,Vì sao Hải Phòng chọn Thủy Nguyên để đặt trung...,negative,0.295917,0.363248,0.340835,0.363248

In [5]:

df = pd.read_csv("data_labeled_snorkel.csv")
print("Gợi ý review tay (confidence <= 0.6):", int((df["confidence"] <= 0.5).sum()))

Gợi ý review tay (confidence <= 0.6): 1921

# Kiểm tra nhãn được gán

In [21]:
cols = ['text', 'pred_label_revised', 'confidence_revised']
view = df[cols]

In [22]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [34]:
df = pd.read_csv("data_annotated.csv")
print("Gợi ý review tay (confidence <= 0.6):", int((df["confidence_revised"] <= 0.6).sum()))

Gợi ý review tay (confidence <= 0.6): 921

In [35]:
df[df["confidence_revised"] <= 0.6]

,text,pred_label_revised,confidence_revised
0,"Sở Giáo dục TPHCM lên tiếng việc 47.000 giáo viên bị kiểm tra trình độ tiếng Anh — Sở GD-ĐT TPHCM khẳng định việc khảo sát tiếng Anh của giáo viên không phải kiểm tra trình độ cá nhân. Kết quả khảo sát tuyệt đối không được sử dụng cho bất kỳ mục đích nào khác như đánh giá thi đua, xét lương, kỷ luật hay các mục đích cá nhân khác.",neutral,0.6
1,"Người mẹ trăn trở trước giờ ghi 'đơn xanh' nguyện vọng thi lớp 10 cho con — Trước sức nóng của kỳ thi vào lớp 10 Hà Nội, chị Nguyễn Thị Hoa (Hà Nội) nhiều ngày qua đau đầu trăn trở, “đặt bút lên lại bỏ xuống” trước những quyết định đăng ký nguyện vọng chọn trường cho con.",neutral,0.6
2,"Màn ‘hỏi xoáy’ bất ngờ của học sinh BRIS với giám đốc Cerberus Esports — Ngoài thể hiện sự tự tin và khả năng trình bày lưu loát bằng tiếng Anh, học sinh tiểu học tại BRIS còn khiến giám đốc Cerberus Esports bất ngờ trước loạt câu hỏi đầy tính phản biện và những ý tưởng kinh doanh cực kỳ sáng tạo.",neutral,0.6
3,"Xây nhà ở nhiều năm trên đất khai hoang có được cấp sổ đỏ? — Thửa đất do ông bà tự khai phá năm 1980 để làm vườn. Năm 2007, ông bà cho con cháu để làm nhà và gia đình đã quản lý ổn định từ đó đến nay. Đất phù hợp quy hoạch nhưng chưa được đăng ký, cấp giấy chứng nhận quyền sử dụng đất lần đầu.",neutral,0.6
4,"Từ chiến sĩ nặng 40kg đến người vẽ bản đồ tác chiến vào 'cánh cửa thép' Xuân Lộc — Cựu chiến binh Đàm Duy Thiên, nguyên trinh sát, người làm công tác bản đồ thuộc Trung đoàn 266, Sư đoàn 341-Sông Lam chia sẻ về công tác vẽ bản đồ tác chiến tấn công vào “cánh cửa thép” Xuân Lộc.",neutral,0.6
5,"Thủy thủ tàu ngầm đọc sách giữa lòng đại dương sâu thẳm — Giữa lòng đại dương sâu thẳm, nơi gần như cách biệt hoàn toàn với thế giới bên ngoài, những thủy thủ tàu ngầm Lữ đoàn 189 duy trì một nét đẹp văn hóa đáng trân trọng.",neutral,0.6
6,"Tổng Bí thư tri ân các tướng lĩnh, anh hùng lực lượng vũ trang — Tổng Bí thư Tô Lâm nhấn mạnh, đại thắng mùa Xuân 1975 mãi mãi là niềm tự hào, là mốc son chói lọi nhất trong lịch sử của dân tộc, một biểu tượng sáng ngời của chủ nghĩa anh hùng cách mạng.",neutral,0.6
7,"Lý do hợp nhất Thái Bình với Hưng Yên, lấy tên tỉnh mới là Hưng Yên — Tên gọi “tỉnh Hưng Yên” sau khi hợp nhất Hưng Yên với Thái Bình là phù hợp, vì địa danh này có bề dày lịch sử, văn hiến và truyền thống cách mạng, xuất hiện từ thời vua Minh Mạng năm 1831.",neutral,0.6
8,"Phu nhân Thủ tướng chia sẻ về Bắc Bling, nghe quan họ với các nhà ngoại giao nữ — Sáng nay, tại tỉnh Bắc Ninh, bà Lê Thị Bích Trân, Phu nhân Thủ tướng Phạm Minh Chính gặp mặt, giao lưu với Nhóm Phụ nữ Cộng đồng ASEAN tại Hà Nội.",neutral,0.6
9,"'Chúng tôi xung trận không phải để thành anh hùng' — ""Chúng tôi còn sống qua chiến tranh là may mắn và cũng là sứ mệnh, sống để tiếp tục cống hiến cho Tổ quốc thay cả phần những đồng đội đã hy sinh"" - nữ Anh hùng Phan Thị Ngọc Tươi chia sẻ.",neutral,0.6
10,"Trao quyết định của Chủ tịch nước cho thiếu tá quân đội đi gìn giữ hòa bình — Sáng 21/4, Bộ Quốc phòng tổ chức trao quyết định của Chủ tịch nước cho sĩ quan đi thực hiện nhiệm vụ gìn giữ hòa bình của Liên Hợp Quốc tại Phái bộ Cộng Hòa Trung Phi (MINUSCA).",neutral,0.6
11,"Công đoàn không phải một phần 'phụ lục' trong bộ máy hành chính — Vấn đề cốt lõi hiện nay là làm sao để công đoàn thực sự độc lập, đại diện và hành động vì người lao động, chứ không phải trở thành một phần “phụ lục” trong bộ máy hành chính.",neutral,0.6
12,"Tổng Bí thư Tô Lâm dự chương trình nghệ thuật 'Đất nước trọn niềm vui' — Tối 20/4, chương trình nghệ thuật Đất nước trọn niềm vui do Quân ủy Trung ương, Bộ Quốc phòng chỉ đạo tổ chức thực hiện kỷ niệm 50 năm thống nhất đất nước. Tổng Bí thư Tô Lâm dự chương trình này.",neutral,0.6
13,"Tổng Bí thư rơi nước mắt trước các bậc lão thành cách mạng miền Nam — Sáng 21/4, Tổng Bí thư Tô Lâm chủ trì buổi gặp mặt của lãnh đạo Đảng, Nhà nước với cán bộ lão thành cách mạng, người có công, gia đình chính sách tiêu biểu miền Nam.",neutral,0.6
14,"Tiềm năng, lợi thế khi 2 tỉnh Thái Bình và Hưng Yên hợp nhất — Việc hợp nhất tỉnh Thái Bình và Hưng Yên sẽ hình thành tỉnh mới có quy mô kinh tế lớn, với sự kết hợp giữa kinh tế biển, nông nghiệp và du lịch; khai thác tối đa tiềm năng, lợi thế về vị trí địa lý.",neutral,0.6
15,"Thiếu tướng Đoàn Hùng Minh: Từ ngày 30/4 nghĩ về những giọt nước mắt — ""Vào dịp 30/4 này, tôi bỗng nhận ra một điều lớn lao: Nước mắt chính là nguồn năng lượng sống mà cả một thế hệ thời chiến đã dâng hiến trọn vẹn cho Tổ quốc"" - Thiếu tướng Đoàn Hùng Minh chia sẻ.",neutral,0.6
16,"Lời hứa 20 năm của Larry Berman với 'điệp viên hoàn hảo' Phạm Xuân Ẩn — Khi viết về Thiếu tướng Phạm Xuân Ẩn, Giáo sư, nhà sử học Larry Berman đã hứa không sử dụng những thông tin có thể làm tổn thương đến nhiều người. Sau gần 20 năm, lời hứa đó vẫn còn.",neutral,0.6
17,"Chuyên gia tập đoàn đa quốc gia hiến kế định vị thương hiệu cho TPHCM — ""Phở, áo dài, đường bờ biển... tất cả yếu tố này cần được chắt lọc và kết tinh thành một thông điệp rõ ràng, có sức lan tỏa để định vị thương hiệu quốc gia và đô thị” - bà Trần Tuệ Tri, thành viên của AVSE Global chia sẻ.",neutral,0.6
18,"Cách tra cứu mã số thuế cá nhân bằng CCCD — Để tra cứu mã số thuế cá nhân, người dân có thể thực hiện dễ dàng và nhanh chóng chỉ với số thẻ căn cước công dân (CCCD) của mình.",neutral,0.6
19,"12 năm sau khi bị lừa tiền, người phụ nữ bất ngờ nhận được cuộc gọi từ tòa án — TRUNG QUỐC - Năm 2013, khi đang học đại học, cô gái bị lừa mất một khoản tiền lớn. Mới đây, cô bất ngờ nhận được cuộc gọi từ tòa án.",neutral,0.6
20,"Phát hiện bí mật của chồng cũ, người phụ nữ lặng người, xin nối lại tình xưa — Nhận hộ chồng cũ cuộc điện thoại, tôi rơi nước mắt khi biết được tấm lòng của anh và thực sự muốn quay lại.",neutral,0.6
21,"Cô dâu Thái Bình nghẹn ngào vì món quà ‘lạ’ và lời nhắn nhủ của 7 chị chồng — Nhận món quà đặc biệt và nghe những lời nhắn nhủ xúc động của 7 người chị chồng trong ngày cưới, cô dâu Thái Bình nghẹn ngào không nói nên lời.",neutral,0.6
22,"Sự hình thành của tuyến đường ống xăng dầu Trường Sơn huyền thoại — Cuối năm 1967 đầu năm 1968, chiến tranh đánh phá miền Bắc của Mỹ vô cùng ác liệt. Khi ấy, tuyến Đường Hồ Chí Minh chuyển sang vận tải bằng cơ giới, xăng dầu vì thế trở thành nhu cầu cực kỳ thiết yếu.",neutral,0.6
23,"Vợ chồng ở Đắk Lắk làm 'căn gác chữa lành' xanh mướt, các con thích mê — Vợ chồng ở Đắk Lắk có một khu vườn 30m2 nằm trên mái sân để xe trước nhà. Khu vườn được họ đặt tên là ""căn gác chữa lành"".",neutral,0.6
24,"Thị trấn 'trốn nóng' kín phòng sớm nhất dịp 30/4, bỏ xa cả Đà Lạt — Cận kề kỳ nghỉ 30/4-1/5, du khách vẫn có thể đặt phòng tại Đà Lạt nhưng Măng Đen và Sa Pa gần như đã kín chỗ.",neutral,0.6
25,"Đặc sản miền Bắc 'hiếm có khó tìm', vị béo ngậy, thơm ngọt, ăn ngon hơn cua đồng — Cứ đến tháng 3 và tháng 10 âm lịch, đặc sản này lại được người dân ở một số tỉnh thành miền Bắc săn đón, mua về chế biến thành loạt món ăn và hương vị được nhận xét là béo ngậy, ngọt ngon hơn cua đồng.",neutral,0.6
26,"Thời điểm vàng để doanh nghiệp vay mua ô tô lãi suất chỉ từ 6,8%/năm — Sản phẩm vay mua ô tô của VPBank được thiết kế linh hoạt, phù hợp với mọi loại hình, quy mô doanh nghiệp SME với mức lãi suất hấp dẫn hàng đầu thị trường, thời gian hoàn tất thủ tục vay siêu ngắn, là lựa chọn tối ưu cho doanh nghiệp SME.",neutral,0.6
27,"Bộ trưởng Tài chính: Linh hoạt rút ngắn hoặc kéo dài thời gian thu phí dự án PPP — “Có những dự án doanh thu chỉ tăng 10-15% đã là rất lớn, đặt ra yêu cầu phải đàm phán lại để rút ngắn thời gian thu phí. Nhưng cũng có dự án doanh thu giảm 10% là nhà đầu tư đã gặp khó khăn” - Bộ trưởng Tài chính Nguyễn Văn Thắng nêu rõ.",neutral,0.6
28,"Giá USD ngân hàng cao chưa từng có, lên sát 26.200 đồng — Tỷ giá USD hôm nay 25/4/2025 ghi nhận giá đồng bạc xanh tại các ngân hàng tăng cao chưa từng có, lên sát mức 26.200 đồng/USD.",neutral,0.6
29,Livestream bán hàng cùng TikTok Shop - giải pháp kinh doanh thương mại số — Livestream bán hàng cùng TikTok Shop không còn là sân chơi của riêng cá nhân hay nhà sáng tạo nội dung. Ngày càng nhiều doanh nghiệp chủ động đầu tư cho hoạt động này như một phần trong chiến lược kinh doanh trực tuyến.,neutral,0.6
30,"Việt Nam bỏ lỡ nguồn thu tỷ đô vì thiếu bến du thuyền — Việt Nam mới chỉ vận hành thử nghiệm bến du thuyền chuẩn quốc tế đầu tiên trong bối cảnh Đông Nam Á đang là điểm đến xu hướng của nhóm du thuyền cá nhân, du lịch tàu biển.",neutral,0.6
31,"13 cách nhận biết vàng thật, vàng giả tại nhà — Vàng được nhiều người lựa chọn để đầu tư, làm đồ trang sức. Nhưng không phải ai cũng biết cách phân biệt vàng thật, vàng giả. Dưới đây là cách nhận biết vàng thật, vàng giả đơn giản, chính xác.",neutral,0.6
32,"Lãi suất ngân hàng hôm nay 25/4/2025: Kỳ hạn 12 tháng ngân hàng nào cao nhất? — Lãi suất ngân hàng hôm nay 25/4/2025, không có ngân hàng nào điều chỉnh lãi suất huy động trong hôm nay, sau khi đã có 6 ngân hàng giảm và 5 ngân hàng tăng lãi suất từ đầu tháng. Gửi tiền kỳ hạn 12 tháng ở đâu để có lãi suất cao nhất?",neutral,0.6
33,"Bánh mì Madam Trang - khởi đầu từ đam mê ẩm thực Việt — Lấy cảm hứng từ tinh thần đổi mới và tình yêu với ẩm thực Việt, của hàng bánh mì Madam Trang mang đến sự kết hợp sáng tạo giữa truyền thống và phong cách hiện đại.",neutral,0.6
34,"Ứng phó nguy cơ Mỹ áp thuế hàng Việt Nam, ngành Hải quan sẽ làm gì? — Cơ quan hải quan sẽ tăng cường kiểm soát chặt chẽ nguồn nguyên liệu đầu vào nhằm ngăn chặn tình trạng hàng hóa nước ngoài 'đội lốt' sản phẩm Việt Nam để xuất khẩu sang Mỹ và các thị trường khác.",neutral,0.6
35,"Bộ đôi MINI Cooper S giá hơn 2 tỷ: Xe sang cá tính nhưng không dành cho số đông — Bộ đôi MINI Cooper S 3 cửa và 5 cửa giữ nguyên phong cách nhỏ gọn, hoài cổ và cá tính đặc trưng. Nhưng giữa thời đại đề cao tính thực dụng, mẫu xe Anh quốc giá hơn 2 tỷ đồng tỏ ra quá kén người chơi và không dành cho số đông.",neutral,0.6
36,5 thói quen tai hại của người dùng khiến hộp số ô tô nhanh hỏng — Hộp số ô tô là một trong những bộ phận quan trọng của xe và cũng là một trong những chi tiết dễ bị hỏng hóc bởi chính những thói quen sai lầm của người dùng.,neutral,0.6
37,"Thanh niên dùng mã tấu chặn đường 2 mẹ con trong đêm — Trên đường đi từ TPHCM về Ninh Thuận, người phụ nữ chở theo con trai lưu thông trên quốc lộ 1A đoạn qua tỉnh Bình Thuận thì bị 2 đối tượng chặn đường, cướp tài sản.",neutral,0.6
38,"Đập vỡ kính 20 ô tô để trộm cắp tài sản ở Hà Nội — Sau khi bị bắt, Đỗ Thanh Mạnh khai từ cuối tháng 3 đến đầu tháng 4, Mạnh đã đập vỡ cửa kính của hơn 20 ô tô, thực hiện hành vi trộm cắp tài sản.",neutral,0.6
39,"Bắt quả tang 13 con bạc say sưa sát phạt qua ván bài Poker ở Cần Thơ — Ập vào quán bida nổi tiếng trong khu dân cư cán bộ giảng viên Đại học Cần Thơ, lực lượng cảnh sát hình sự bắt quả tang nhiều đối tượng đang đánh chơi Poker ăn thua bằng tiền.",neutral,0.6
40,"Bắt giữ 5 đối tượng điều hành đường dây đánh bạc hơn 100 tỷ đồng — Đường dây đánh bạc qua mạng bằng hình thức cá độ bóng đá với số tiền giao dịch hơn 100 tỷ đồng vừa bị công an triệt phá, bắt 5 đối tượng.",neutral,0.6
41,"Công an vượt hơn 1km đường rừng đưa sản phụ sinh con trong rẫy ra trạm y tế — Ngày 28/4, UBND xã Phước Tân (huyện Sơn Hòa, Phú Yên) cho biết, lực lượng công an của xã vừa đưa một sản phụ sinh con trong rẫy ra Trạm Y tế xã Phước Tân để tiếp tục chăm sóc.",neutral,0.6
42,"Vụ clip bịa đặt về Bệnh viện Bạch Mai, đề nghị công an vào cuộc điều tra — Bệnh viện Bạch Mai cho biết đã đề nghị cơ quan Công an điều tra về những thông tin, hình ảnh bịa đặt về bệnh viện lan truyền trên mạng.",neutral,0.6
43,"Bộ Y tế chỉ đạo khẩn vụ điều dưỡng bị hành hung khi đang cấp cứu — Cục Quản lý Khám, chữa bệnh đề nghị Giám đốc Sở Y tế Phú Thọ khẩn trương chỉ đạo các đơn vị liên quan phối hợp với các cơ quan thực thi pháp luật làm rõ, xử lý nghiêm vụ người nhà bệnh nhân hành hung nhân viên y tế.",neutral,0.6
44,"5 trường hợp bác sĩ được quyền từ chối khám chữa cho bệnh nhân — Sự việc các y, bác sĩ đang cấp cứu bệnh nhi bị người nhà gào thét, dùng lời lẽ công kích, chửi bậy thậm chí đạp vào bụng khiến cộng đồng bức xúc. Nhiều người băn khoăn, khi nào thầy thuốc có quyền từ chối khám chữa cho bệnh nhân.",neutral,0.6
45,"Cách hạ sốt phổ biến khiến bé trai bất động, phải đi cấp cứu — Khi trẻ bị sốt, nhiều phụ huynh thường nghĩ đến việc dùng khăn lạnh để hạ nhiệt. Tuy nhiên, một em nhỏ đã phải đi cấp cứu sau khi được mẹ chăm sóc như vậy.",neutral,0.6
46,"Ông Trump tuyên bố sẽ không tranh cử tổng thống Mỹ nhiệm kỳ 3 — Tổng thống Mỹ Donald Trump đã công khai loại trừ khả năng tranh cử nhiệm kỳ 3 dù trước đó nhiều lần ám chỉ việc này. Khi kết thúc nhiệm kỳ hiện tại, ông Trump sẽ bước sang tuổi 82.",neutral,0.6
47,"Máy bay không người lái Ukraine tấn công nhiều vùng của Nga — Gleb Nikitin, Thống đốc vùng Nizhny Novgorov của Nga cho biết, các máy bay không người lái (UAV) của Ukraine đã tấn công thành phố Dzerzhinsk thuộc vùng này vào ban đêm.",neutral,0.6
48,"Nghị sĩ Mỹ đòi luận tội Tổng thống Trump — Nghị sĩ Dân chủ Shri Thanedar cáo buộc Tổng thống Donald Trump không chiến đấu vì Mỹ mà chỉ đang ""phá hoại và gây nguy hiểm cho nền dân chủ"" của nước này.",neutral,0.6
49,"Bộ trưởng Tài chính hé lộ nước đầu tiên sẽ ký thỏa thuận thương mại với Mỹ — Bộ trưởng Tài chính Scott Bessent khẳng định các cuộc đàm phán về thuế quan của Mỹ vẫn đang tiến triển tốt, đặc biệt là với các đối tác thương mại ở châu Á.",neutral,0.6
50,"Tiêm kích trên tàu sân bay Mỹ rơi xuống Biển Đỏ — Giới chức Mỹ cho hay, một chiếc tiêm kích F/A-18E Super Hornet đã rơi từ tàu sân bay USS Harry S. Truman xuống Biển Đỏ.",neutral,0.6
51,"Leo thang tấn công, chiến lược mặc cả hay ảo vọng hòa bình cho xung đột Ukraine? — Việc Nga và Ukraine tăng cường tấn công các mục tiêu của nhau là dấu hiệu cho thấy sự leo thang đối địch giữa hai bên. Khi cuộc xung đột bước sang năm thứ 4, triển vọng hòa bình vẫn là ẩn số vì các toan tính chiến lược và áp lực chính trị.",neutral,0.6
52,"Không con cái, cụ bà ngoài 90 tuổi vẫn làm việc toàn thời gian — Ở độ tuổi 90, vẫn miệt mài đi làm, cụ bà Yasuko Tamaki – nhân viên văn phòng lớn tuổi nhất thế giới – đã khiến mọi người ngưỡng mộ với nghị lực phi thường.",neutral,0.6
53,"Sở thú Hàn Quốc 'đau đầu' vì thú cưng của cựu Tổng thống Yoon Suk-yeol — Sở thú Seoul Grand Park của Hàn Quốc đang ""đau đầu"" với 2 chú chó của cựu Tổng thống Yoon Suk-yeol, khi chi phí nuôi dưỡng hàng năm của chúng tiêu tốn tới 6,7 triệu Won (hơn 120 triệu đồng).",neutral,0.6
54,"Xuân Son, Văn Hậu có hành động ý nghĩa ngày thống nhất đất nước — Nguyễn Xuân Son cùng nhiều cầu thủ Việt Nam có hành động ý nghĩa trong ngày kỷ niệm 50 năm Giải phóng miền Nam, thống nhất đất nước 30/4.",neutral,0.6
55,"Link xem trực tiếp bóng đá CAHN vs PSM Makassar, 19h30 hôm nay 30/4 — Cung cấp link xem trực tiếp bóng đá CAHN vs PSM Makassar, ở lượt về bán kết ASEAN Club Championship 2024/25, 19h30 hôm nay (30/4).",neutral,0.6
56,"Tuyển Việt Nam: Cơ hội nào cho cầu thủ Việt kiều Viktor Lê? — Chưa dừng lại ở việc được triệu tập cho U22 Việt Nam, cầu thủ Việt kiều Viktor Lê đang đứng trước cơ hội lần đầu được khoác áo ĐTQG.",neutral,0.6
57,"Tranh cãi Thanh Thúy bỏ Cúp thế giới dự SEA Games — Các trụ cột của VTV Bình Điền Long An là Thanh Thúy, Kim Thoa, Khánh Đang... có thể không tham dự Cúp CLB thế giới 2025 vì cùng tuyển bóng chyền nữ Việt Nam 'săn' HCV SEA Games 33.",neutral,0.6
58,"Nhận định bóng đá Barca vs Inter: Đỉnh cao bán kết Cúp C1 — Nhận định bóng đá Barca vs Inter: Barca tấn công và Inter phòng ngự, hứa hẹn so tài đỉnh cao ở lượt đi bán kết Cúp C1.",neutral,0.6
59,"Real Madrid bất ngờ ngăn Ancelotti dẫn tuyển Brazil — Thỏa thuận giữa Carlo Ancelotti và Brazil có nguy cơ đổ bể, khi Real Madrid ngăn cản nhà cầm quân người Italia ra đi tự do.",neutral,0.6
60,Tuyển Việt Nam: Ông Kim Sang Sik chờ gì từ Công Phượng? — Công Phượng có thể trở lại tuyển Việt Nam trong đợt tập trung tới đây và điều mà HLV Kim Sang Sik chờ ở cựu tiền đạo HAGL không chỉ là việc… ghi bàn.,neutral,0.6
61,"Dembele lập đại công, PSG giành lợi thế trước Arsenal — Dembele ghi bàn duy nhất giúp PSG thắng nghẹt thở Arsenal, qua đó giành lợi thế trước trận bán kết lượt về Champions League trên sân Parc des Princes.",neutral,0.6
62,"Xử lý bãi giữ xe ở quận 3 thu 100.000 đồng/lượt dịp lễ diễu binh — Clip mạng xã hội phản ánh, một địa điểm thu 100.000 đồng/xe máy khi người dân đi xem diễu binh, diễu hành và chính quyền đã vào cuộc xử lý.",neutral,0.6
63,"TPHCM cấm xe tải vào 5 đường cửa ngõ trong 6 ngày — Nhiều tuyến đường ở cửa ngõ phía tây TPHCM bị cấm xe tải lưu thông trong 6 ngày để phục vụ Đại lễ Phật đản Vesak Liên Hiệp Quốc năm 2025, diễn ra tại Học viện Phật giáo Việt Nam.",neutral,0.6
64,Khoảnh khắc tiêm kích Su-30MK2 thả bẫy nhiệt rực rỡ trên bầu trời TPHCM sáng 30/4 — Màn biểu diễn thả bẫy nhiệt của tiêm kích Su-30MK2 trên bầu trời TPHCM sáng 30/4 khiến người xem vô cùng phấn khích.,neutral,0.6
65,"Phát hiện thi thể trên sông có giấy tờ ghi tên Trần Văn Luyện — Người dân xã Trung Hà (huyện Yên Lạc, Vĩnh Phúc) phát hiện thi thể người đàn ông kèm giấy tờ tùy thân có tên Trần Văn Luyện tại khu vực ven sông Hồng.",neutral,0.6
66,"Loạt công trình giao thông thay đổi diện mạo TPHCM — Metro Bến Thành - Suối Tiên, cầu Ba Son, cầu Phú Mỹ, nhà ga T3 Tân Sơn Nhất... là những công trình giao thông lớn giúp thay đổi diện mạo TPHCM trong 50 năm qua.",neutral,0.6
67,"Ca sĩ Đức Phúc làm từ thiện nửa tỷ đồng tỏ lòng biết ơn hậu đại lễ 30/4 — Nhằm tỏ lòng biết ơn vào đại lễ 30/4, ca sĩ Đức Phúc cho đi 500 triệu đồng làm từ thiện.",neutral,0.6
68,"Hoa hậu 4 con Jennifer Phạm vai trần gợi cảm, Quách Thu Phương U50 trẻ trung — Hoa hậu Jennifer Phạm khoe vẻ gợi cảm với váy trễ vai khi đi nghỉ dưỡng cùng gia đình. Diễn viên Quách Thu Phương trẻ trung bên con trai.",neutral,0.6
69,"3 giọng hát Đà Lạt 'như rót mật ngọt', một người 18 năm mới trở lại — Tuấn Ngọc, Trung Quân Idol và Nguyên Thảo đều sinh ra và lớn lên tại Đà Lạt, có giọng hát mang theo âm hưởng đặc trưng của phố núi, tạo nên phong cách biểu diễn riêng biệt.",neutral,0.6
70,Nghệ sĩ Hương Thanh - em gái danh ca Hương Lan 'tái xuất' — Nghệ sĩ Hương Thanh - em gái Hương Lan - từ Pháp về nước tham gia đêm nhạc đặc biệt cùng các nghệ sĩ Nguyên Lê và Mieko Miyazaki (Nhật Bản) với loạt ca khúc dân ca phối jazz.,neutral,0.6
71,"Cặp vợ chồng hát hay, tình và cuốn hút mới xuất hiện showbiz Việt là ai? — Showbiz Việt vừa xuất hiện cặp vợ chồng nghệ sĩ song ca mới - Minh Quân và Thu Thuỷ. Họ không chỉ trẻ đẹp về ngoại hình mà còn hát hay, tình và cuốn hút.",neutral,0.6
72,"Lý do hoa hậu 22 tuổi gốc miền Tây gác lại chuyện yêu đương — Tạm gác tình yêu để theo đuổi sứ mệnh văn hóa, Hoa hậu Quốc gia Việt Nam Kiều Duy chỉ tin vào một chữ ""duyên"" và sự đồng cảm giữa hai trái tim.",neutral,0.6
73,"Nữ VĐV bóng chuyền cao 1,91m, giỏi 4 ngoại ngữ thi Miss Universe 2025 là ai? — CROATIA - Với chiều cao nổi bật 1,91m và học vấn ấn tượng, Hoa hậu Hoàn vũ Croatia - Laura Gnjatović được kỳ vọng sẽ đạt thành tích cao tại Miss Universe 2025.",neutral,0.6
74,"Nữ NSND mang quân hàm Đại tá gây sốt với bức ảnh mặc quân phục ở tuổi 56 — Bức ảnh NSND Thu Quế mặc quân phục đứng chào cờ với dòng chia sẻ ""Hướng tới Đại lễ 30/4"" hút 10.000 lượt thích.",neutral,0.6
75,"Rộ tin Tom Cruise hẹn hò nữ diễn viên kém 26 tuổi siêu sexy — Tom Cruise và Bondgirl Ana de Armas nhiều lần bị bắt gặp đi cùng nhau. Sau khi đưa đón bạn gái tin đồn bằng trực thăng, Tom Cruise ở London cùng Ana de Armas nguyên ngày sinh nhật của cô.",neutral,0.6
76,"Chiêm ngưỡng báu vật hơn 300 năm được chạm khắc gỗ độc nhất vô nhị ở Bắc Giang — Bức cửa võng đình làng Thổ Hà có tuổi đời hơn 300 năm, là một kiệt tác nghệ thuật chạm khắc gỗ độc nhất vô nhị.",neutral,0.6
77,"Vụ hành hung cô giáo, y bác sĩ: Nỗi đau không của riêng nạn nhân — Hai vụ hành hung liên tiếp gần đây dù trong bối cảnh khác nhau nhưng đều khiến nhiều người nhói đau bởi nơi xảy ra là nhà trường, bệnh viện và nạn nhân là cô giáo, y bác sĩ.",neutral,0.6

In [23]:
from IPython.display import display
display(view)

                                                                                                                                                                                                                                                                                                                                                           text  \
0                   Sở Giáo dục TPHCM lên tiếng việc 47.000 giáo viên bị kiểm tra trình độ tiếng Anh — Sở GD-ĐT TPHCM khẳng định việc khảo sát tiếng Anh của giáo viên không phải kiểm tra trình độ cá nhân. Kết quả khảo sát tuyệt đối không được sử dụng cho bất kỳ mục đích nào khác như đánh giá thi đua, xét lương, kỷ luật hay các mục đích cá nhân khác.
1                                                                              Người mẹ trăn trở trước giờ ghi 'đơn xanh' nguyện vọng thi lớp 10 cho con — Trước sức nóng của kỳ thi vào lớp 10 Hà Nội, chị Nguyễn Thị Hoa (Hà Nội) nhiều ngày qua đau đầu trăn trở, “đặt bút lên lại bỏ xuống” trước những quyết định đăng ký nguyện vọng chọn trường cho con.
2                                                    Màn ‘hỏi xoáy’ bất ngờ của học sinh BRIS với giám đốc Cerberus Esports — Ngoài thể hiện sự tự tin và khả năng trình bày lưu loát bằng tiếng Anh, học sinh tiểu học tại BRIS còn khiến giám đốc Cerberus Esports bất ngờ trước loạt câu hỏi đầy tính phản biện và những ý tưởng kinh doanh cực kỳ sáng tạo.
3                                                        Xây nhà ở nhiều năm trên đất khai hoang có được cấp sổ đỏ? — Thửa đất do ông bà tự khai phá năm 1980 để làm vườn. Năm 2007, ông bà cho con cháu để làm nhà và gia đình đã quản lý ổn định từ đó đến nay. Đất phù hợp quy hoạch nhưng chưa được đăng ký, cấp giấy chứng nhận quyền sử dụng đất lần đầu.
4                                                                        Từ chiến sĩ nặng 40kg đến người vẽ bản đồ tác chiến vào 'cánh cửa thép' Xuân Lộc — Cựu chiến binh Đàm Duy Thiên, nguyên trinh sát, người làm công tác bản đồ thuộc Trung đoàn 266, Sư đoàn 341-Sông Lam chia sẻ về công tác vẽ bản đồ tác chiến tấn công vào “cánh cửa thép” Xuân Lộc.
5                                                                                                                              Thủy thủ tàu ngầm đọc sách giữa lòng đại dương sâu thẳm — Giữa lòng đại dương sâu thẳm, nơi gần như cách biệt hoàn toàn với thế giới bên ngoài, những thủy thủ tàu ngầm Lữ đoàn 189 duy trì một nét đẹp văn hóa đáng trân trọng.
6                                                                                                 Tổng Bí thư tri ân các tướng lĩnh, anh hùng lực lượng vũ trang — Tổng Bí thư Tô Lâm nhấn mạnh, đại thắng mùa Xuân 1975 mãi mãi là niềm tự hào, là mốc son chói lọi nhất trong lịch sử của dân tộc, một biểu tượng sáng ngời của chủ nghĩa anh hùng cách mạng.
7                                                                                            Lý do hợp nhất Thái Bình với Hưng Yên, lấy tên tỉnh mới là Hưng Yên — Tên gọi “tỉnh Hưng Yên” sau khi hợp nhất Hưng Yên với Thái Bình là phù hợp, vì địa danh này có bề dày lịch sử, văn hiến và truyền thống cách mạng, xuất hiện từ thời vua Minh Mạng năm 1831.
8                                                                                                                          Phu nhân Thủ tướng chia sẻ về Bắc Bling, nghe quan họ với các nhà ngoại giao nữ — Sáng nay, tại tỉnh Bắc Ninh, bà Lê Thị Bích Trân, Phu nhân Thủ tướng Phạm Minh Chính gặp mặt, giao lưu với Nhóm Phụ nữ Cộng đồng ASEAN tại Hà Nội.
9                                                                                                              'Chúng tôi xung trận không phải để thành anh hùng' — "Chúng tôi còn sống qua chiến tranh là may mắn và cũng là sứ mệnh, sống để tiếp tục cống hiến cho Tổ quốc thay cả phần những đồng đội đã hy sinh" - nữ Anh hùng Phan Thị Ngọc Tươi chia sẻ.
10                                                                                              Trao quyết định của Chủ tịch nước cho thiếu tá quân đội đi gìn giữ hòa bình — Sáng 21/4, Bộ Quốc phòng tổ chức trao quyết định của Chủ tịch nước cho sĩ quan đi thực hiện nhiệm vụ gìn giữ hòa bình của Liên Hợp Quốc tại Phái bộ Cộng Hòa Trung Phi (MINUSCA).
11                                                                                                             Công đoàn không phải một phần 'phụ lục' trong bộ máy hành chính — Vấn đề cốt lõi hiện nay là làm sao để công đoàn thực sự độc lập, đại diện và hành động vì người lao động, chứ không phải trở thành một phần “phụ lục” trong bộ máy hành chính.
12                                                                                 Tổng Bí thư Tô Lâm dự chương trình nghệ thuật 'Đất nước trọn niềm vui' — Tối 20/4, chương trình nghệ thuật Đất nước trọn niềm vui do Quân ủy Trung ương, Bộ Quốc phòng chỉ đạo tổ chức thực hiện kỷ niệm 50 năm thống nhất đất nước. Tổng Bí thư Tô Lâm dự chương trình này.
13                                                                                                                  Tổng Bí thư rơi nước mắt trước các bậc lão thành cách mạng miền Nam — Sáng 21/4, Tổng Bí thư Tô Lâm chủ trì buổi gặp mặt của lãnh đạo Đảng, Nhà nước với cán bộ lão thành cách mạng, người có công, gia đình chính sách tiêu biểu miền Nam.
14                                                                                        Tiềm năng, lợi thế khi 2 tỉnh Thái Bình và Hưng Yên hợp nhất — Việc hợp nhất tỉnh Thái Bình và Hưng Yên sẽ hình thành tỉnh mới có quy mô kinh tế lớn, với sự kết hợp giữa kinh tế biển, nông nghiệp và du lịch; khai thác tối đa tiềm năng, lợi thế về vị trí địa lý.
15                                                                                    Thiếu tướng Đoàn Hùng Minh: Từ ngày 30/4 nghĩ về những giọt nước mắt — "Vào dịp 30/4 này, tôi bỗng nhận ra một điều lớn lao: Nước mắt chính là nguồn năng lượng sống mà cả một thế hệ thời chiến đã dâng hiến trọn vẹn cho Tổ quốc" - Thiếu tướng Đoàn Hùng Minh chia sẻ.
16                                                                                               Lời hứa 20 năm của Larry Berman với 'điệp viên hoàn hảo' Phạm Xuân Ẩn — Khi viết về Thiếu tướng Phạm Xuân Ẩn, Giáo sư, nhà sử học Larry Berman đã hứa không sử dụng những thông tin có thể làm tổn thương đến nhiều người. Sau gần 20 năm, lời hứa đó vẫn còn.
17                                                        Chuyên gia tập đoàn đa quốc gia hiến kế định vị thương hiệu cho TPHCM — "Phở, áo dài, đường bờ biển... tất cả yếu tố này cần được chắt lọc và kết tinh thành một thông điệp rõ ràng, có sức lan tỏa để định vị thương hiệu quốc gia và đô thị” - bà Trần Tuệ Tri, thành viên của AVSE Global chia sẻ.
18                                                                                                                                                                               Cách tra cứu mã số thuế cá nhân bằng CCCD — Để tra cứu mã số thuế cá nhân, người dân có thể thực hiện dễ dàng và nhanh chóng chỉ với số thẻ căn cước công dân (CCCD) của mình.
19                                                                                                                                         12 năm sau khi bị lừa tiền, người phụ nữ bất ngờ nhận được cuộc gọi từ tòa án — TRUNG QUỐC - Năm 2013, khi đang học đại học, cô gái bị lừa mất một khoản tiền lớn. Mới đây, cô bất ngờ nhận được cuộc gọi từ tòa án.
20                                                                                                                                                                   Phát hiện bí mật của chồng cũ, người phụ nữ lặng người, xin nối lại tình xưa — Nhận hộ chồng cũ cuộc điện thoại, tôi rơi nước mắt khi biết được tấm lòng của anh và thực sự muốn quay lại.
21                                                                                                                                Cô dâu Thái Bình nghẹn ngào vì món quà ‘lạ’ và lời nhắn nhủ của 7 chị chồng — Nhận món quà đặc biệt và nghe những lời nhắn nhủ xúc động của 7 người chị chồng trong ngày cưới, cô dâu Thái Bình nghẹn ngào không nói nên lời.
22                                                                                  Sự hình thành của tuyến đường ống xăng dầu Trường Sơn huyền thoại — Cuối năm 1967 đầu năm 1968, chiến tranh đánh phá miền Bắc của Mỹ vô cùng ác liệt. Khi ấy, tuyến Đường Hồ Chí Minh chuyển sang vận tải bằng cơ giới, xăng dầu vì thế trở thành nhu cầu cực kỳ thiết yếu.
23                                                                                                                                                          Vợ chồng ở Đắk Lắk làm 'căn gác chữa lành' xanh mướt, các con thích mê — Vợ chồng ở Đắk Lắk có một khu vườn 30m2 nằm trên mái sân để xe trước nhà. Khu vườn được họ đặt tên là "căn gác chữa lành".
24                                                                                                                                                                            Thị trấn 'trốn nóng' kín phòng sớm nhất dịp 30/4, bỏ xa cả Đà Lạt — Cận kề kỳ nghỉ 30/4-1/5, du khách vẫn có thể đặt phòng tại Đà Lạt nhưng Măng Đen và Sa Pa gần như đã kín chỗ.
25                                                                 Đặc sản miền Bắc 'hiếm có khó tìm', vị béo ngậy, thơm ngọt, ăn ngon hơn cua đồng — Cứ đến tháng 3 và tháng 10 âm lịch, đặc sản này lại được người dân ở một số tỉnh thành miền Bắc săn đón, mua về chế biến thành loạt món ăn và hương vị được nhận xét là béo ngậy, ngọt ngon hơn cua đồng.
26                                         Thời điểm vàng để doanh nghiệp vay mua ô tô lãi suất chỉ từ 6,8%/năm — Sản phẩm vay mua ô tô của VPBank được thiết kế linh hoạt, phù hợp với mọi loại hình, quy mô doanh nghiệp SME với mức lãi suất hấp dẫn hàng đầu thị trường, thời gian hoàn tất thủ tục vay siêu ngắn, là lựa chọn tối ưu cho doanh nghiệp SME.
27                             Bộ trưởng Tài chính: Linh hoạt rút ngắn hoặc kéo dài thời gian thu phí dự án PPP — “Có những dự án doanh thu chỉ tăng 10-15% đã là rất lớn, đặt ra yêu cầu phải đàm phán lại để rút ngắn thời gian thu phí. Nhưng cũng có dự án doanh thu giảm 10% là nhà đầu tư đã gặp khó khăn” - Bộ trưởng Tài chính Nguyễn Văn Thắng nêu rõ.
28                                                                                                                                                                      Giá USD ngân hàng cao chưa từng có, lên sát 26.200 đồng — Tỷ giá USD hôm nay 25/4/2025 ghi nhận giá đồng bạc xanh tại các ngân hàng tăng cao chưa từng có, lên sát mức 26.200 đồng/USD.
29                                                      Livestream bán hàng cùng TikTok Shop - giải pháp kinh doanh thương mại số — Livestream bán hàng cùng TikTok Shop không còn là sân chơi của riêng cá nhân hay nhà sáng tạo nội dung. Ngày càng nhiều doanh nghiệp chủ động đầu tư cho hoạt động này như một phần trong chiến lược kinh doanh trực tuyến.
30                                                                                                                          Việt Nam bỏ lỡ nguồn thu tỷ đô vì thiếu bến du thuyền — Việt Nam mới chỉ vận hành thử nghiệm bến du thuyền chuẩn quốc tế đầu tiên trong bối cảnh Đông Nam Á đang là điểm đến xu hướng của nhóm du thuyền cá nhân, du lịch tàu biển.
31                                                                                                            13 cách nhận biết vàng thật, vàng giả tại nhà — Vàng được nhiều người lựa chọn để đầu tư, làm đồ trang sức. Nhưng không phải ai cũng biết cách phân biệt vàng thật, vàng giả. Dưới đây là cách nhận biết vàng thật, vàng giả đơn giản, chính xác.
32                                   Lãi suất ngân hàng hôm nay 25/4/2025: Kỳ hạn 12 tháng ngân hàng nào cao nhất? — Lãi suất ngân hàng hôm nay 25/4/2025, không có ngân hàng nào điều chỉnh lãi suất huy động trong hôm nay, sau khi đã có 6 ngân hàng giảm và 5 ngân hàng tăng lãi suất từ đầu tháng. Gửi tiền kỳ hạn 12 tháng ở đâu để có lãi suất cao nhất?
33                                                                                                                                  Bánh mì Madam Trang - khởi đầu từ đam mê ẩm thực Việt — Lấy cảm hứng từ tinh thần đổi mới và tình yêu với ẩm thực Việt, của hàng bánh mì Madam Trang mang đến sự kết hợp sáng tạo giữa truyền thống và phong cách hiện đại.
34                                                                                     Ứng phó nguy cơ Mỹ áp thuế hàng Việt Nam, ngành Hải quan sẽ làm gì? — Cơ quan hải quan sẽ tăng cường kiểm soát chặt chẽ nguồn nguyên liệu đầu vào nhằm ngăn chặn tình trạng hàng hóa nước ngoài 'đội lốt' sản phẩm Việt Nam để xuất khẩu sang Mỹ và các thị trường khác.
35                                          Bộ đôi MINI Cooper S giá hơn 2 tỷ: Xe sang cá tính nhưng không dành cho số đông — Bộ đôi MINI Cooper S 3 cửa và 5 cửa giữ nguyên phong cách nhỏ gọn, hoài cổ và cá tính đặc trưng. Nhưng giữa thời đại đề cao tính thực dụng, mẫu xe Anh quốc giá hơn 2 tỷ đồng tỏ ra quá kén người chơi và không dành cho số đông.
36                                                                                                                              5 thói quen tai hại của người dùng khiến hộp số ô tô nhanh hỏng — Hộp số ô tô là một trong những bộ phận quan trọng của xe và cũng là một trong những chi tiết dễ bị hỏng hóc bởi chính những thói quen sai lầm của người dùng.
37                                                                                                                                  Thanh niên dùng mã tấu chặn đường 2 mẹ con trong đêm — Trên đường đi từ TPHCM về Ninh Thuận, người phụ nữ chở theo con trai lưu thông trên quốc lộ 1A đoạn qua tỉnh Bình Thuận thì bị 2 đối tượng chặn đường, cướp tài sản.
38                                                                                                                                                          Đập vỡ kính 20 ô tô để trộm cắp tài sản ở Hà Nội — Sau khi bị bắt, Đỗ Thanh Mạnh khai từ cuối tháng 3 đến đầu tháng 4, Mạnh đã đập vỡ cửa kính của hơn 20 ô tô, thực hiện hành vi trộm cắp tài sản.
39                                                                                                        Bắt quả tang 13 con bạc say sưa sát phạt qua ván bài Poker ở Cần Thơ — Ập vào quán bida nổi tiếng trong khu dân cư cán bộ giảng viên Đại học Cần Thơ, lực lượng cảnh sát hình sự bắt quả tang nhiều đối tượng đang đánh chơi Poker ăn thua bằng tiền.
40                                                                                                                                                 Bắt giữ 5 đối tượng điều hành đường dây đánh bạc hơn 100 tỷ đồng — Đường dây đánh bạc qua mạng bằng hình thức cá độ bóng đá với số tiền giao dịch hơn 100 tỷ đồng vừa bị công an triệt phá, bắt 5 đối tượng.
41                                                                                                Công an vượt hơn 1km đường rừng đưa sản phụ sinh con trong rẫy ra trạm y tế — Ngày 28/4, UBND xã Phước Tân (huyện Sơn Hòa, Phú Yên) cho biết, lực lượng công an của xã vừa đưa một sản phụ sinh con trong rẫy ra Trạm Y tế xã Phước Tân để tiếp tục chăm sóc.
42                                                                                                                                           Vụ clip bịa đặt về Bệnh viện Bạch Mai, đề nghị công an vào cuộc điều tra — Bệnh viện Bạch Mai cho biết đã đề nghị cơ quan Công an điều tra về những thông tin, hình ảnh bịa đặt về bệnh viện lan truyền trên mạng.
43                                                                   Bộ Y tế chỉ đạo khẩn vụ điều dưỡng bị hành hung khi đang cấp cứu — Cục Quản lý Khám, chữa bệnh đề nghị Giám đốc Sở Y tế Phú Thọ khẩn trương chỉ đạo các đơn vị liên quan phối hợp với các cơ quan thực thi pháp luật làm rõ, xử lý nghiêm vụ người nhà bệnh nhân hành hung nhân viên y tế.
44                                                       5 trường hợp bác sĩ được quyền từ chối khám chữa cho bệnh nhân — Sự việc các y, bác sĩ đang cấp cứu bệnh nhi bị người nhà gào thét, dùng lời lẽ công kích, chửi bậy thậm chí đạp vào bụng khiến cộng đồng bức xúc. Nhiều người băn khoăn, khi nào thầy thuốc có quyền từ chối khám chữa cho bệnh nhân.
45                                                                                                                                   Cách hạ sốt phổ biến khiến bé trai bất động, phải đi cấp cứu — Khi trẻ bị sốt, nhiều phụ huynh thường nghĩ đến việc dùng khăn lạnh để hạ nhiệt. Tuy nhiên, một em nhỏ đã phải đi cấp cứu sau khi được mẹ chăm sóc như vậy.
46                                                                                                         Ông Trump tuyên bố sẽ không tranh cử tổng thống Mỹ nhiệm kỳ 3 — Tổng thống Mỹ Donald Trump đã công khai loại trừ khả năng tranh cử nhiệm kỳ 3 dù trước đó nhiều lần ám chỉ việc này. Khi kết thúc nhiệm kỳ hiện tại, ông Trump sẽ bước sang tuổi 82.
47                                                                                                                      Máy bay không người lái Ukraine tấn công nhiều vùng của Nga — Gleb Nikitin, Thống đốc vùng Nizhny Novgorov của Nga cho biết, các máy bay không người lái (UAV) của Ukraine đã tấn công thành phố Dzerzhinsk thuộc vùng này vào ban đêm.
48                                                                                                                                                        Nghị sĩ Mỹ đòi luận tội Tổng thống Trump — Nghị sĩ Dân chủ Shri Thanedar cáo buộc Tổng thống Donald Trump không chiến đấu vì Mỹ mà chỉ đang "phá hoại và gây nguy hiểm cho nền dân chủ" của nước này.
49                                                                                                                    Bộ trưởng Tài chính hé lộ nước đầu tiên sẽ ký thỏa thuận thương mại với Mỹ — Bộ trưởng Tài chính Scott Bessent khẳng định các cuộc đàm phán về thuế quan của Mỹ vẫn đang tiến triển tốt, đặc biệt là với các đối tác thương mại ở châu Á.
50                                                                                                                                                                                    Tiêm kích trên tàu sân bay Mỹ rơi xuống Biển Đỏ — Giới chức Mỹ cho hay, một chiếc tiêm kích F/A-18E Super Hornet đã rơi từ tàu sân bay USS Harry S. Truman xuống Biển Đỏ.
51                           Leo thang tấn công, chiến lược mặc cả hay ảo vọng hòa bình cho xung đột Ukraine? — Việc Nga và Ukraine tăng cường tấn công các mục tiêu của nhau là dấu hiệu cho thấy sự leo thang đối địch giữa hai bên. Khi cuộc xung đột bước sang năm thứ 4, triển vọng hòa bình vẫn là ẩn số vì các toan tính chiến lược và áp lực chính trị.
52                                                                                                                                 Không con cái, cụ bà ngoài 90 tuổi vẫn làm việc toàn thời gian — Ở độ tuổi 90, vẫn miệt mài đi làm, cụ bà Yasuko Tamaki – nhân viên văn phòng lớn tuổi nhất thế giới – đã khiến mọi người ngưỡng mộ với nghị lực phi thường.
53                                                                                      Sở thú Hàn Quốc 'đau đầu' vì thú cưng của cựu Tổng thống Yoon Suk-yeol — Sở thú Seoul Grand Park của Hàn Quốc đang "đau đầu" với 2 chú chó của cựu Tổng thống Yoon Suk-yeol, khi chi phí nuôi dưỡng hàng năm của chúng tiêu tốn tới 6,7 triệu Won (hơn 120 triệu đồng).
54                                                                                                                                                  Xuân Son, Văn Hậu có hành động ý nghĩa ngày thống nhất đất nước — Nguyễn Xuân Son cùng nhiều cầu thủ Việt Nam có hành động ý nghĩa trong ngày kỷ niệm 50 năm Giải phóng miền Nam, thống nhất đất nước 30/4.